runtime: go
api_version: go1
instance_class: B4
basic_scaling:
  max_instances: 1
  idle_timeout: 1m

handlers:
- url: /tasks/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
  secure: always